attack_name: moeva
budget: 300
dirs:
  results: ./data/malware/out/
eps_list:
- 0.1
initial_state_offset: 0
misclassification_threshold: 0.9
n_initial_state: 1717
n_offsprings: 100
n_pop: 200
norm: 2
paths:
  attack_results: ./2.npy
  constraints: ./data/malware/constraints.csv
  features: ./data/malware/features.csv
  min_max_scaler: ./data/malware/malware_scaler.joblib
  ml_scaler: None
  model: ./models/malware/rf_model_clean.joblib
  x_candidates: ./data/malware/adversarial_cand_train/adversarial_cand_4500_leftover.npy
project_name: malware
reconstruction: false
save_history: reduced
unconstrained: false
seed: 42
system:
  n_jobs: 20
  verbose: 1
